addSbtPlugin("org.scalameta"      % "sbt-scalafmt"       % "2.6.1")
addSbtPlugin("com.github.sbt"     % "sbt-ci-release"     % "1.12.0")
addSbtPlugin("com.github.sbt"     % "sbt-header"         % "5.11.0")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"        % "1.22.0")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"            % "0.4.8")
addSbtPlugin("com.github.sbt"     % "sbt-osgi"           % "0.11.0-RC1")
addSbtPlugin("org.scala-native"   % "sbt-scala-native"   % "0.5.12")
addSbtPlugin("com.github.sbt"     % "sbt-github-actions" % "0.31.0")
